title: "Patch & Pot"
description: "Beginner-friendly, mindful growing for small spaces."
url: "https://patchandpot.com"
baseurl: ""

logo: /img/patchandpot-logo.png

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

# Build from /sites folder
source: sites
destination: _site

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

timezone: Europe/London
