title: "Patch & Pot"
url: "https://patchandpot.com"
baseurl: ""
source: sites
permalink: "/:path/:basename:output_ext"
markdown: kramdown
kramdown: { input: GFM }
plugins: []
include: [".htaccess","js","img","data","_layouts","_includes"]
exclude: ["node_modules","README.md",".gitignore",".github","Gemfile","Gemfile.lock"]
