# Patch & Pot — Jekyll Config

title: "Patch & Pot"
description: "Beginner-friendly, mindful growing for small spaces."
url: "https://patchandpot.com"
baseurl: ""

# Logo path (PNG)
logo: /img/patchandpot-logo.png

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

include:
  - .htaccess
  - _pages

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

timezone: Europe/London
