title: "Patch & Pot"
description: "Beginner-friendly, mindful growing for small spaces."
url: "https://patchandpot.com"
baseurl: ""

# Build from /sites
source: sites
destination: _site

# Logo now under assets/img
logo: /assets/img/patchandpot-logo.png

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

timezone: Europe/London
