# Patch & Pot — Jekyll config (CLEAN, SINGLE SOURCE OF TRUTH)
title: "Patch & Pot"
url: "https://patchandpot.com"
baseurl: ""              # custom domain at site root
source: sites            # build from /sites

# Keep .html links EXACTLY as written in your pages
permalink: "/:path/:basename:output_ext"

markdown: kramdown
kramdown:
  input: GFM

plugins: []              # keep empty for GH Pages runner

# Make sure Jekyll sees these folders under /sites
include:
  - .htaccess
  - js
  - img
  - data
  - _layouts
  - _includes
  - css
  - assets
  - pdf

# Keep these out of the build
exclude:
  - node_modules
  - vendor
  - .github
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
