# ------------------------------------------
# Patch & Pot — Jekyll configuration (root)
# ------------------------------------------

title: "Patch & Pot"
description: "Grow food and calm in small spaces."
url: "https://patchandpot.com"
baseurl: ""                 # custom domain at root

# Build from /sites (you’re using Actions, so this is fine)
source: sites

# Permalinks & Markdown
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM

# Keep GH Pages happy (no custom plugins)
plugins: []

# Include (relative to /sites). Normal folders don’t need listing,
# but we’ll keep any non-standard/dotfiles explicit.
include:
  - .htaccess
  - partials
  - js
  - img
  - data
  - _layouts

# Exclude from processing
exclude:
  - node_modules
  - .github
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor
