# Root Jekyll config (repo builds the site from /sites)
title: "Patch & Pot"
url: "https://patchandpot.com"
baseurl: ""         # domain points to /sites, so keep empty

# IMPORTANT: tell Jekyll where the site lives
source: sites

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM

# Make sure Jekyll processes plain .html with front matter under /sites
include:
  - .htaccess
  - partials
  - js
  - img
  - data
  - _layouts
