# ------------------------------------------
# Patch & Pot — Jekyll configuration
# ------------------------------------------

title: "Patch & Pot"
url: "https://patchandpot.com"
baseurl: ""

# Tell Jekyll to use /sites as the source directory
source: sites

# Permalink structure
permalink: pretty

# Markdown engine
markdown: kramdown
kramdown:
  input: GFM

# Include directories required for site build
include:
  - .htaccess
  - partials
  - js
  - img
  - data
  - _layouts

# Exclude things that shouldn't be processed
exclude:
  - node_modules
  - README.md
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
