name: GitHub Pages (build from /sites)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree + config (for sanity)
        run: |
          echo "=== ROOT ==="; ls -la
          echo; echo "=== SITES ==="; ls -la sites || true
          echo; echo "=== _config.yml (root) ==="; sed -n '1,200p' _config.yml || true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install gems (explicit)
        run: |
          cat > Gemfile <<'RUBY'
          source "https://rubygems.org"
          gem "jekyll", "~> 4.3"
          gem "kramdown-parser-gfm", "~> 1.1"
          gem "webrick", "~> 1.8"
          RUBY
          bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll (from /sites)
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll --version
          set -o pipefail
          bundle exec jekyll build \
            --config _config.yml \
            --source sites \
            --destination _site \
            --trace --verbose | tee buildlog.txt

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: buildlog.txt

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
